WIP  - ENG 1648  - Refactor refresh logic, refresh data and types
SphereGlobal/WebSDK pull request #59
Opened 2023-09-18 02:42 UTC by JuanSphereOne

2023-09-18 21:49 UTC, DavidYangSphere1 reviewed
@JuanSphereOne , please see my comments below. Thank you!

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +    this.user = null;
@JuanSphereOne , like my comment above, I think you need to decide to either use `null` or `undefined` and stick with that.

I see no reason why we have an object, a `undefined`, and a `null` be possible values.

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +        this.getWallets();
@JuanSphereOne , these five function calls are being repeated four times --> here, on lines 194 to 198, on lines 144 to 148, and on lines 238 to 242.

Create a private function, like:
```ts
#loadUserData = async () => {
  this.getUserInfo();
  this.getTransactions();
  this.getNfts();
  this.getBalances();
  this.getWallets();
}
```

That way, you can simply reuse them as a one-liner.

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  #fetchUserBalances = async (): Promise<UserBalance | never> => {
@JuanSphereOne , why is this a `never`?

`never` means that this type will NEVER be able to conform with the specified type.

Can `void` not be used instead of `never`?

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  #fetchUserWallets = async (): Promise<WalletDoc[] | never> => {
@JuanSphereOne , same here.

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  #fetchUserInfo = async (): Promise<Info | {} | Error> => {
@JuanSphereOne , why is this completely different from the above two?

For `Promises`, we simply do `Promise<Info>`. Any errors are not included as part of the return type.

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  #getWrappedDek = async (): Promise<string | null> => {
@JuanSphereOne , how could this be `nullable` if you are forcefully type-casting the result into a `string`?

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  #fetchTransactions = async (): Promise<string | undefined> => {
@JuanSphereOne , same here. How could this be `optional` if you are type-casting `data.data` to a `string`.

You're lucky this isn't Java or Kotlin. Otherwise, this project would never build.

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +  createCharge = async (charge: ChargeReqBody): Promise<ChargeUrlAndId | null> => {
@JuanSphereOne , same here.

You can only do `Promise<ChargeUrlAndId | null>` ONLY IF you do something like:
```ts
try {
  if (data.error) throw new Error(data.error);
  else return data.data as ChargeUrlAndId;
} catch (e: any) {
  console.error(e);
  return null;
}
```

2023-09-18 21:49 UTC, DavidYangSphere1 commented on index.ts
> +      return await this.checkTokenAndExecuteFunction(payChargeFn);
@JuanSphereOne , what is this `checkTokenAndExecuteFunction`?

I'm assuming this is similar to the Interceptor logic, checking the token's expiry time per call, right?

If so, why couldn't you simply put this logic in the `#createRequest` function? Isn't that being used for all possible API calls in this websdk? Couldn't you put your logic there instead of this weird function?

2023-09-18 22:26 UTC, DavidYangSphere1 commented
@JuanSphereOne , I forgot 1 thing.

Can you quickly update the `SupportedChains` enum in the webSdk, so they properly reflect what we have in the backend?
Here's updated list (+ Flow chain)
```ts
enum SupportedChains {
  ETHEREUM = "ETHEREUM",
  SOLANA = "SOLANA",
  POLYGON = "POLYGON",
  OPTIMISM = "OPTIMISM",
  AVALANCHE = "AVALANCHE",
  ARBITRUM = "ARBITRUM",
  BINANCE = "BINANCE",
  IMMUTABLE = "IMMUTABLE",
  FANTOM = "FANTOM",
  GNOSIS = "GNOSIS",
  FLOW = "FLOW"
}
```

2023-09-19 06:04 UTC, JuanSphereOne commented on index.ts
> +  baseUrl?: string = 'https://api-olgsdff53q-uc.a.run.app';
Hi @DavidYangSphere1 ! I think that would help us with the testing part, for example, if we want to test the websdk in testing, we can add the baseUrl of our api in staging. Let me know what you think.

2023-09-19 06:06 UTC, JuanSphereOne commented on index.ts
> +  user?: User | null | undefined = undefined;
This idea was taken from the libraries we are using in the frontend, like Dashboard, App, Checkout, etc. When the page is loaded, first it is as undefined (so we know it is "loading") and then, if there is a user, it is load and if not the user is null. I forgot to change it in the "clear" method, sorry about that.

2023-09-19 06:08 UTC, JuanSphereOne commented on index.ts
> +      return await this.checkTokenAndExecuteFunction(payChargeFn);
Yes, that is what this functions is doing. I have moved it to the createRequest as you recommended, thanks you!

2023-09-19 06:20 UTC, JuanSphereOne commented
@DavidYangSphere1 Thanks for your comments. I know that there were a lot of mistakes in this PR, sorry about that and thanks for the patience and the help to get this code better. I think that really help me with types.  
Please take a look when you have some time!

2023-09-19 14:08 UTC, DavidYangSphere1 commented on index.ts
> +  user?: User | null | undefined = undefined;
@JuanSphereOne , hmm, but we're not doing that here, right?

Also, even if we do have a loading state, we don't need to have three different values, such as `undefined`, `null`, and an actual object.

What we're doing in the frontend is wrong, to begin with.

In the frontend, we should simply have two values: either user has a value or not. If the api call fails, we shouldn't set the user to `null`. We should keep the existing data and see if it's possible to make another API call while showing an error message to user.

Otherwise, the frontend will look like something completely went wrong, instead of just an API call not working.

2023-09-19 14:32 UTC, JuanSphereOne commented on index.ts
> +  baseUrl?: string = 'https://api-olgsdff53q-uc.a.run.app';
Oh! Just the typing, Ok. Changed

2023-09-19 14:52 UTC, davidw-sphereone requested changes

2023-09-19 14:52 UTC, davidw-sphereone commented on index.ts
> +          this.#loadUserData();
duplicate logic, refactor into loadCredentials function mentioned above

2023-09-19 14:52 UTC, davidw-sphereone commented on index.ts
> +        this.#loadUserData();
duplicate logic, refactor into loadCredentials function mentioned above

2023-09-19 14:52 UTC, davidw-sphereone commented on index.ts
>    #pwaDevUrl = 'http://localhost:19006';
I say we remove all dev and staging URLs - these were just for our local testing. Currently, they serve no purpose. We could also remove #environment (it will always be Production by default).  What do you think? @DavidYangSphere1

2023-09-19 14:59 UTC, davidw-sphereone commented
I would like us to refactor how we instantiate the SDK. We should remove the setters, and instead pass the setup args as a constructor. This would remove the need for a build function.

This is more inline with how most SDKs are instantiated. 

Example

![Screenshot 2023-09-19 at 9 54 36 AM](https://github.com/SphereGlobal/WebSDK/assets/140534226/25a9bb17-4108-4675-84ac-8db45d6f5406)

Another example (Thirdweb SDK)

![Screenshot 2023-09-19 at 9 58 42 AM](https://github.com/SphereGlobal/WebSDK/assets/140534226/9de0a1a0-43b4-4821-af8f-bbc53b1e41aa)

https://portal.thirdweb.com/typescript/getting-started

2023-09-19 15:08 UTC, davidw-sphereone requested changes

2023-09-19 15:08 UTC, davidw-sphereone commented on src/types.ts
>  export interface Info {
Lets rename this to UserInfo

2023-09-19 15:08 UTC, davidw-sphereone commented on src/types.ts
> +  invitedBy: null | string;
Couldn't this be simplified to 
`invitedBy?: string`

do we even use this property? @DavidYangSphere1

2023-09-19 15:08 UTC, davidw-sphereone commented on src/types.ts
> +  data: WalletDoc[] | null;
Lets rename the WalletDoc type to Wallet

2023-09-19 16:42 UTC, JuanSphereOne commented on src/types.ts
> +  invitedBy: null | string;
It is not being used any more so we can just remove that

2023-09-19 16:43 UTC, JuanSphereOne commented on src/types.ts
> +  invitedBy: null | string;
But I think that it can be null or string because if it is in our DB, Firebase does not support undefined.

2023-09-19 19:12 UTC, davidw-sphereone commented on src/types.ts
> +  invitedBy: null | string;
Lets remove it then

2023-09-19 21:00 UTC, davidw-sphereone requested changes

2023-09-19 21:13 UTC, DavidYangSphere1 approved these changes
@JuanSphereOne , looks fine to me.

2023-09-19 21:13 UTC, merged